spring:
  redis:
#    host: 127.0.0.1
#    port: 6379
    password:
    timeout: 7200
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
     #集群
    cluster:
      nodes: 127.0.0.1:6379
server:
  port: 8081
